const http = require('node:http');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '0.0.0.0';
const PUBLIC = path.join(__dirname, 'public');
const DB_FILE = process.env.DB_FILE || path.join(__dirname, 'data', 'collegeox.db');
const OWNER_HASH = '4b13c0ad44c34477a59a7378ef014801:242d00119ea47b3a36ca500cde6c9eff80f608a1da76fbd2d17f23e0ff525cd5';
const SESSION_MS = 1000 * 60 * 60 * 24 * 14;
const streams = new Set();
const rateBuckets = new Map();

fs.mkdirSync(path.dirname(DB_FILE), { recursive: true });
const db = new DatabaseSync(DB_FILE);
db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
db.exec(`
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE, email TEXT UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'student', bio TEXT NOT NULL DEFAULT '', department TEXT NOT NULL DEFAULT '', year TEXT NOT NULL DEFAULT '', pronouns TEXT NOT NULL DEFAULT '', location TEXT NOT NULL DEFAULT '', avatar TEXT NOT NULL DEFAULT '', accent TEXT NOT NULL DEFAULT '#155eef', interests TEXT NOT NULL DEFAULT '[]', links TEXT NOT NULL DEFAULT '[]', profile_visibility TEXT NOT NULL DEFAULT 'campus', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS follows (follower_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, following_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TEXT NOT NULL, PRIMARY KEY(follower_id,following_id));
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, body TEXT NOT NULL, type TEXT NOT NULL, tags TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL, edited_at TEXT);
CREATE TABLE IF NOT EXISTS reactions (post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind TEXT NOT NULL, PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE, author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, pitch TEXT NOT NULL, skills TEXT NOT NULL DEFAULT '[]', capacity INTEGER NOT NULL DEFAULT 4, status TEXT NOT NULL DEFAULT 'recruiting', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_members (project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, joined_at TEXT NOT NULL, PRIMARY KEY(project_id,user_id));
CREATE TABLE IF NOT EXISTS clubs (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL UNIQUE COLLATE NOCASE, description TEXT NOT NULL, category TEXT NOT NULL, accent TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS club_members (club_id TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, joined_at TEXT NOT NULL, PRIMARY KEY(club_id,user_id));
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT NOT NULL, starts_at TEXT NOT NULL, location TEXT NOT NULL, capacity INTEGER NOT NULL DEFAULT 100, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_attendees (event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, joined_at TEXT NOT NULL, PRIMARY KEY(event_id,user_id));
CREATE TABLE IF NOT EXISTS announcements (id TEXT PRIMARY KEY, author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, body TEXT NOT NULL, audience TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS issues (id TEXT PRIMARY KEY, reporter_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, subject TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', admin_note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id,created_at);
CREATE INDEX IF NOT EXISTS idx_follows_following ON follows(following_id);
CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status,created_at DESC);
`);

const now = () => new Date().toISOString();
const id = prefix => `${prefix}_${crypto.randomBytes(9).toString('base64url')}`;
const json = (value, fallback = []) => { try { return JSON.parse(value); } catch { return fallback; } };
const hashPassword = (password, salt = crypto.randomBytes(16).toString('hex')) => `${salt}:${crypto.pbkdf2Sync(password, salt, 210000, 32, 'sha256').toString('hex')}`;
const verifyPassword = (password, stored) => { const [salt, digest] = stored.split(':'); const candidate = crypto.pbkdf2Sync(password, salt, 210000, 32, 'sha256'); return digest?.length === 64 && crypto.timingSafeEqual(candidate, Buffer.from(digest, 'hex')); };
const tokenHash = token => crypto.createHash('sha256').update(token).digest('hex');
const clean = (value, max = 500) => String(value || '').trim().slice(0, max);
const safeUser = row => row ? ({ id: row.id, username: row.username, email: row.email || '', name: row.name, role: row.role, bio: row.bio, department: row.department, year: row.year, pronouns: row.pronouns, location: row.location, avatar: row.avatar, accent: row.accent, interests: json(row.interests), links: json(row.links), profileVisibility: row.profile_visibility, createdAt: row.created_at }) : null;
function publicUser(row,viewerId){const out=safeUser(row);if(!out)return null;if(row.id!==viewerId)delete out.email;if(row.id!==viewerId&&row.profile_visibility==='private'){out.bio='';out.department='';out.year='';out.pronouns='';out.location='';out.interests=[];out.links=[];out.private=true}return out}

if (!db.prepare('SELECT id FROM users WHERE role=?').get('owner')) db.prepare(`INSERT INTO users (id,username,email,password_hash,name,role,bio,accent,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).run('owner_navi', 'Navi', null, OWNER_HASH, 'Navi', 'owner', '', '#155eef', now());

function send(res, status, payload) { const out = JSON.stringify(payload); res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': Buffer.byteLength(out) }); res.end(out); }
function readBody(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > 900000) reject(Object.assign(new Error('Request too large'), { status: 413 })); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(Object.assign(new Error('Invalid JSON'), { status: 400 })); } }); req.on('error', reject); }); }
function cookieMap(req) { return Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(x => { const p = x.trim().split('='); return [decodeURIComponent(p.shift()), decodeURIComponent(p.join('='))]; })); }
function currentUser(req) { const token = cookieMap(req).collegeox_session; if (!token) return null; return db.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).get(tokenHash(token), Date.now()) || null; }
function startSession(res, userId) { const token = crypto.randomBytes(32).toString('base64url'); db.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now()); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(tokenHash(token), userId, Date.now() + SESSION_MS); res.setHeader('Set-Cookie', `collegeox_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${SESSION_MS / 1000}${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`); }
function endSession(req, res) { const token = cookieMap(req).collegeox_session; if (token) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(tokenHash(token)); res.setHeader('Set-Cookie', 'collegeox_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'); }
function originAllowed(req) { const origin = req.headers.origin; if (!origin) return true; try { return new URL(origin).host === req.headers.host; } catch { return false; } }
function rate(req, bucket, max, windowMs = 60000) { const key = `${bucket}:${req.socket.remoteAddress || 'local'}`; const t = Date.now(); let item = rateBuckets.get(key); if (!item || item.reset < t) item = { count: 0, reset: t + windowMs }; item.count++; rateBuckets.set(key, item); return item.count <= max; }
const requireRole = (user, roles) => user && roles.includes(user.role);
function broadcast(kind, payload = {}) { const message = `event: ${kind}\ndata: ${JSON.stringify({ kind, ...payload })}\n\n`; for (const stream of streams) { try { stream.write(message); } catch { streams.delete(stream); } } }

function postRows(userId, where = '', params = []) {
  const rows = db.prepare(`SELECT p.*,u.username,u.name,u.role,u.avatar,u.accent,u.department,(SELECT COUNT(*) FROM reactions r WHERE r.post_id=p.id) reaction_count,(SELECT kind FROM reactions r WHERE r.post_id=p.id AND r.user_id=?) reacted,(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id) comment_count,EXISTS(SELECT 1 FROM follows f WHERE f.follower_id=? AND f.following_id=p.author_id) following_author FROM posts p JOIN users u ON u.id=p.author_id ${where} ORDER BY p.created_at DESC LIMIT 100`).all(userId,userId, ...params);
  const commentStmt = db.prepare(`SELECT c.*,u.username,u.name,u.role,u.avatar,u.accent FROM comments c JOIN users u ON u.id=c.author_id WHERE c.post_id=? ORDER BY c.created_at ASC`);
  return rows.map(r => ({ id:r.id,body:r.body,type:r.type,tags:json(r.tags),createdAt:r.created_at,editedAt:r.edited_at,reactionCount:r.reaction_count,reacted:r.reacted||null,commentCount:r.comment_count,followingAuthor:!!r.following_author,author:{id:r.author_id,username:r.username,name:r.name,role:r.role,avatar:r.avatar,accent:r.accent,department:r.department},comments:commentStmt.all(r.id).map(c=>({id:c.id,body:c.body,createdAt:c.created_at,author:{id:c.author_id,username:c.username,name:c.name,role:c.role,avatar:c.avatar,accent:c.accent}})) }));
}
function profilePayload(target, viewerId) { const counts=db.prepare(`SELECT (SELECT COUNT(*) FROM follows WHERE following_id=?) followers,(SELECT COUNT(*) FROM follows WHERE follower_id=?) following,(SELECT COUNT(*) FROM posts WHERE author_id=?) posts`).get(target.id,target.id,target.id); const followed=viewerId?!!db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND following_id=?').get(viewerId,target.id):false; return {user:publicUser(target,viewerId),counts,followed}; }
const listProjects = userId => db.prepare(`SELECT p.*,u.username,u.name,(SELECT COUNT(*) FROM project_members m WHERE m.project_id=p.id) members,EXISTS(SELECT 1 FROM project_members m WHERE m.project_id=p.id AND m.user_id=?) joined FROM projects p JOIN users u ON u.id=p.owner_id ORDER BY p.created_at DESC`).all(userId).map(r=>({...r,skills:json(r.skills)}));
const listClubs = userId => db.prepare(`SELECT c.*,u.username,(SELECT COUNT(*) FROM club_members m WHERE m.club_id=c.id) members,EXISTS(SELECT 1 FROM club_members m WHERE m.club_id=c.id AND m.user_id=?) joined FROM clubs c JOIN users u ON u.id=c.owner_id ORDER BY c.created_at DESC`).all(userId);
const listEvents = userId => db.prepare(`SELECT e.*,u.username,(SELECT COUNT(*) FROM event_attendees a WHERE a.event_id=e.id) attendees,EXISTS(SELECT 1 FROM event_attendees a WHERE a.event_id=e.id AND a.user_id=?) going FROM events e JOIN users u ON u.id=e.creator_id WHERE e.starts_at>=? ORDER BY e.starts_at`).all(userId,now());

async function aiAssist(input, user) {
  if (!process.env.OPENAI_API_KEY) throw Object.assign(new Error('AI is not configured yet. Add OPENAI_API_KEY on the server to enable it.'), { status: 503 });
  const mode=['rewrite','summarize','brainstorm','moderate'].includes(input.mode)?input.mode:'rewrite';
  const instructions={rewrite:'Improve clarity and tone while preserving meaning. Return only the revised text.',summarize:'Summarize into concise action items. Return only the summary.',brainstorm:'Suggest five practical campus-focused ideas. Be concise.',moderate:'Assess this campus post for harassment, hate, sexual content, self-harm, threats, spam, or personal data. Return compact JSON with allowed boolean, categories array, and reason.'}[mode];
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',instructions:`${instructions} You are assisting ${user.name} inside a college community platform.`,input:clean(input.text,5000),max_output_tokens:500})});
  if(!response.ok)throw Object.assign(new Error('The AI provider could not complete that request.'),{status:502});const data=await response.json();return data.output_text||data.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'';
}

async function api(req,res,pathname,url){
  const method=req.method,user=currentUser(req);if(method!=='GET'&&!originAllowed(req))return send(res,403,{error:'Origin rejected'});
  if(pathname==='/api/health')return send(res,200,{ok:true,database:'sqlite',realtime:true,ai:!!process.env.OPENAI_API_KEY});
  if(pathname==='/api/auth/login'&&method==='POST'){if(!rate(req,'login',10))return send(res,429,{error:'Too many sign-in attempts. Try again in one minute.'});const input=await readBody(req),login=clean(input.login,120);const found=db.prepare('SELECT * FROM users WHERE username=? COLLATE NOCASE OR email=? COLLATE NOCASE').get(login,login);if(!found||!verifyPassword(String(input.password||''),found.password_hash))return send(res,401,{error:'Those sign-in details do not match an account.'});startSession(res,found.id);return send(res,200,{user:safeUser(found)});}
  if(pathname==='/api/auth/register'&&method==='POST'){if(!rate(req,'register',6,300000))return send(res,429,{error:'Too many account attempts. Please wait.'});const input=await readBody(req),username=clean(input.username,24),email=clean(input.email,160).toLowerCase(),password=String(input.password||''),name=clean(input.name,60);if(!/^[a-zA-Z0-9_.]{3,24}$/.test(username))return send(res,400,{error:'Username must be 3–24 letters, numbers, dots, or underscores.'});if(!/^\S+@\S+\.\S+$/.test(email)||password.length<10||!name)return send(res,400,{error:'Add your name, campus email, and a password of at least 10 characters.'});if(db.prepare('SELECT 1 FROM users WHERE username=? COLLATE NOCASE OR email=? COLLATE NOCASE').get(username,email))return send(res,409,{error:'That username or email is already in use.'});const next={id:id('usr'),username,email,password:hashPassword(password),name};db.prepare(`INSERT INTO users (id,username,email,password_hash,name,role,created_at) VALUES (?,?,?,?,?,'student',?)`).run(next.id,next.username,next.email,next.password,next.name,now());startSession(res,next.id);return send(res,201,{user:safeUser(db.prepare('SELECT * FROM users WHERE id=?').get(next.id))});}
  if(pathname==='/api/auth/logout'&&method==='POST'){endSession(req,res);return send(res,200,{ok:true});}
  if(pathname==='/api/me')return send(res,200,{user:safeUser(user),aiEnabled:!!process.env.OPENAI_API_KEY});
  if(!user)return send(res,401,{error:'Sign in required.'});
  if(pathname==='/api/stream'&&method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform',Connection:'keep-alive','X-Accel-Buffering':'no'});res.write('event: ready\ndata: {"ok":true}\n\n');streams.add(res);const ping=setInterval(()=>res.write(': ping\n\n'),25000);req.on('close',()=>{clearInterval(ping);streams.delete(res)});return;}
  if(pathname==='/api/bootstrap')return send(res,200,{user:safeUser(user),aiEnabled:!!process.env.OPENAI_API_KEY,posts:postRows(user.id),projects:listProjects(user.id),clubs:listClubs(user.id),events:listEvents(user.id),announcements:db.prepare(`SELECT a.*,u.username,u.name FROM announcements a JOIN users u ON u.id=a.author_id ORDER BY a.created_at DESC LIMIT 50`).all(),counts:{people:db.prepare('SELECT COUNT(*) n FROM users').get().n,posts:db.prepare('SELECT COUNT(*) n FROM posts').get().n,clubs:db.prepare('SELECT COUNT(*) n FROM clubs').get().n}});
  if(pathname==='/api/profile'&&method==='PATCH'){const input=await readBody(req),username=clean(input.username,24);if(!/^[a-zA-Z0-9_.]{3,24}$/.test(username))return send(res,400,{error:'Choose a valid username.'});if(db.prepare('SELECT id FROM users WHERE username=? COLLATE NOCASE AND id<>?').get(username,user.id))return send(res,409,{error:'That username is taken.'});const avatar=String(input.avatar||'');if(avatar&&(!avatar.startsWith('data:image/')||avatar.length>650000))return send(res,400,{error:'Profile image must be under 450 KB.'});const interests=Array.isArray(input.interests)?input.interests.slice(0,12).map(x=>clean(x,28)).filter(Boolean):[],links=Array.isArray(input.links)?input.links.slice(0,5).map(x=>({label:clean(x.label,30),url:clean(x.url,300)})).filter(x=>/^https?:\/\//.test(x.url)):[];db.prepare(`UPDATE users SET username=?,name=?,bio=?,department=?,year=?,pronouns=?,location=?,avatar=?,accent=?,interests=?,links=?,profile_visibility=? WHERE id=?`).run(username,clean(input.name,60)||user.name,clean(input.bio,300),clean(input.department,80),clean(input.year,30),clean(input.pronouns,30),clean(input.location,80),avatar,/^#[0-9a-fA-F]{6}$/.test(input.accent||'')?input.accent:'#155eef',JSON.stringify(interests),JSON.stringify(links),input.profileVisibility==='private'?'private':'campus',user.id);const updated=db.prepare('SELECT * FROM users WHERE id=?').get(user.id);broadcast('profile',{userId:user.id});return send(res,200,{user:safeUser(updated)});}
  let match=pathname.match(/^\/api\/profiles\/([^/]+)$/);if(match&&method==='GET'){const target=db.prepare('SELECT * FROM users WHERE username=? COLLATE NOCASE').get(decodeURIComponent(match[1]));if(!target)return send(res,404,{error:'Profile not found.'});const privateView=target.id!==user.id&&target.profile_visibility==='private';return send(res,200,{...profilePayload(target,user.id),posts:privateView?[]:postRows(user.id,'WHERE p.author_id=?',[target.id]),private:privateView});}
  if(pathname==='/api/users/search'&&method==='GET'){const q=clean(url.searchParams.get('q'),60);if(!q)return send(res,200,{users:[]});const rows=db.prepare(`SELECT * FROM users WHERE username LIKE ? OR name LIKE ? OR department LIKE ? ORDER BY CASE WHEN username=? COLLATE NOCASE THEN 0 ELSE 1 END,name LIMIT 30`).all(`%${q}%`,`%${q}%`,`%${q}%`,q);return send(res,200,{users:rows.map(r=>profilePayload(r,user.id))});}
  match=pathname.match(/^\/api\/users\/([^/]+)\/follow$/);if(match&&method==='POST'){if(match[1]===user.id)return send(res,400,{error:'You cannot follow yourself.'});const exists=db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND following_id=?').get(user.id,match[1]);if(exists)db.prepare('DELETE FROM follows WHERE follower_id=? AND following_id=?').run(user.id,match[1]);else db.prepare('INSERT INTO follows VALUES (?,?,?)').run(user.id,match[1],now());broadcast('follow',{userId:match[1]});return send(res,200,{following:!exists});}
  if(pathname==='/api/posts'&&method==='POST'){const input=await readBody(req),text=clean(input.body,1800);if(!text)return send(res,400,{error:'Write something before publishing.'});if(process.env.OPENAI_API_KEY){const verdict=await aiAssist({mode:'moderate',text},user);try{const parsed=JSON.parse(verdict.slice(verdict.indexOf('{'),verdict.lastIndexOf('}')+1));if(parsed.allowed===false)return send(res,422,{error:`This post was held by AI moderation: ${clean(parsed.reason,240)||'unsafe content detected.'}`})}catch{throw Object.assign(new Error('AI moderation returned an unreadable result. The post was not published.'),{status:502})}}const tags=(Array.isArray(input.tags)?input.tags:[]).slice(0,6).map(x=>clean(x.replace(/[^\w-]/g,''),24)).filter(Boolean),postId=id('post');db.prepare('INSERT INTO posts (id,author_id,body,type,tags,created_at) VALUES (?,?,?,?,?,?)').run(postId,user.id,text,['post','question','collab','update'].includes(input.type)?input.type:'post',JSON.stringify(tags),now());broadcast('post',{postId});return send(res,201,{post:postRows(user.id,'WHERE p.id=?',[postId])[0],moderated:!!process.env.OPENAI_API_KEY});}
  match=pathname.match(/^\/api\/posts\/([^/]+)$/);if(match&&method==='DELETE'){const post=db.prepare('SELECT * FROM posts WHERE id=?').get(match[1]);if(!post)return send(res,404,{error:'Post not found.'});if(post.author_id!==user.id&&!requireRole(user,['owner','management']))return send(res,403,{error:'You cannot delete this post.'});db.prepare('DELETE FROM posts WHERE id=?').run(match[1]);broadcast('deletePost',{postId:match[1]});return send(res,200,{ok:true});}
  match=pathname.match(/^\/api\/posts\/([^/]+)\/react$/);if(match&&method==='POST'){const input=await readBody(req),existing=db.prepare('SELECT kind FROM reactions WHERE post_id=? AND user_id=?').get(match[1],user.id);if(existing)db.prepare('DELETE FROM reactions WHERE post_id=? AND user_id=?').run(match[1],user.id);if(!existing||existing.kind!==input.kind)db.prepare('INSERT INTO reactions VALUES (?,?,?)').run(match[1],user.id,['like','spark','support'].includes(input.kind)?input.kind:'like');broadcast('reaction',{postId:match[1]});return send(res,200,{post:postRows(user.id,'WHERE p.id=?',[match[1]])[0]});}
  match=pathname.match(/^\/api\/posts\/([^/]+)\/comments$/);if(match&&method==='POST'){const input=await readBody(req),text=clean(input.body,600);if(!text)return send(res,400,{error:'Comment cannot be empty.'});db.prepare('INSERT INTO comments VALUES (?,?,?,?,?)').run(id('com'),match[1],user.id,text,now());broadcast('comment',{postId:match[1]});return send(res,201,{post:postRows(user.id,'WHERE p.id=?',[match[1]])[0]});}
  if(pathname==='/api/projects'&&method==='POST'){const input=await readBody(req),name=clean(input.name,80),pitch=clean(input.pitch,600);if(!name||!pitch)return send(res,400,{error:'Project name and pitch are required.'});const pid=id('prj');db.prepare('INSERT INTO projects VALUES (?,?,?,?,?,?,?,?)').run(pid,user.id,name,pitch,JSON.stringify((input.skills||[]).slice(0,8).map(x=>clean(x,24))),Math.min(30,Math.max(2,Number(input.capacity)||4)),'recruiting',now());db.prepare('INSERT INTO project_members VALUES (?,?,?)').run(pid,user.id,now());broadcast('project',{id:pid});return send(res,201,{ok:true});}
  match=pathname.match(/^\/api\/projects\/([^/]+)\/join$/);if(match&&method==='POST'){const exists=db.prepare('SELECT 1 FROM project_members WHERE project_id=? AND user_id=?').get(match[1],user.id);if(exists)db.prepare('DELETE FROM project_members WHERE project_id=? AND user_id=?').run(match[1],user.id);else{const p=db.prepare('SELECT capacity,(SELECT COUNT(*) FROM project_members WHERE project_id=?) n FROM projects WHERE id=?').get(match[1],match[1]);if(!p)return send(res,404,{error:'Project not found.'});if(p.n>=p.capacity)return send(res,409,{error:'This team is full.'});db.prepare('INSERT INTO project_members VALUES (?,?,?)').run(match[1],user.id,now())}broadcast('project',{id:match[1]});return send(res,200,{joined:!exists});}
  if(pathname==='/api/clubs'&&method==='POST'){const input=await readBody(req);if(!clean(input.name)||!clean(input.description))return send(res,400,{error:'Club name and description are required.'});const cid=id('club');try{db.prepare('INSERT INTO clubs VALUES (?,?,?,?,?,?,?)').run(cid,user.id,clean(input.name,80),clean(input.description,500),clean(input.category,40)||'Community',/^#[0-9a-fA-F]{6}$/.test(input.accent||'')?input.accent:'#ff6b4a',now());db.prepare('INSERT INTO club_members VALUES (?,?,?)').run(cid,user.id,now())}catch{return send(res,409,{error:'A club with that name already exists.'})}broadcast('club',{id:cid});return send(res,201,{ok:true});}
  match=pathname.match(/^\/api\/clubs\/([^/]+)\/join$/);if(match&&method==='POST'){const exists=db.prepare('SELECT 1 FROM club_members WHERE club_id=? AND user_id=?').get(match[1],user.id);if(exists)db.prepare('DELETE FROM club_members WHERE club_id=? AND user_id=?').run(match[1],user.id);else db.prepare('INSERT INTO club_members VALUES (?,?,?)').run(match[1],user.id,now());broadcast('club',{id:match[1]});return send(res,200,{joined:!exists});}
  if(pathname==='/api/events'&&method==='POST'){const input=await readBody(req);if(!clean(input.title)||!input.startsAt)return send(res,400,{error:'Event title and date are required.'});const eid=id('evt');db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?,?,?)').run(eid,user.id,clean(input.title,100),clean(input.description,800),new Date(input.startsAt).toISOString(),clean(input.location,120),Math.min(5000,Math.max(2,Number(input.capacity)||100)),now());db.prepare('INSERT INTO event_attendees VALUES (?,?,?)').run(eid,user.id,now());broadcast('event',{id:eid});return send(res,201,{ok:true});}
  match=pathname.match(/^\/api\/events\/([^/]+)\/rsvp$/);if(match&&method==='POST'){const exists=db.prepare('SELECT 1 FROM event_attendees WHERE event_id=? AND user_id=?').get(match[1],user.id);if(exists)db.prepare('DELETE FROM event_attendees WHERE event_id=? AND user_id=?').run(match[1],user.id);else db.prepare('INSERT INTO event_attendees VALUES (?,?,?)').run(match[1],user.id,now());broadcast('event',{id:match[1]});return send(res,200,{going:!exists});}
  if(pathname==='/api/announcements'&&method==='POST'){if(!requireRole(user,['owner','management','faculty']))return send(res,403,{error:'Only faculty and management can publish announcements.'});const input=await readBody(req);if(!clean(input.title)||!clean(input.body))return send(res,400,{error:'Title and message are required.'});const aid=id('ann');db.prepare('INSERT INTO announcements VALUES (?,?,?,?,?,?)').run(aid,user.id,clean(input.title,120),clean(input.body,1000),clean(input.audience,30)||'Everyone',now());broadcast('announcement',{id:aid});return send(res,201,{ok:true});}
  if(pathname==='/api/issues'&&method==='POST'){const input=await readBody(req);if(!clean(input.subject)||!clean(input.description))return send(res,400,{error:'Add a subject and explain the issue.'});const iid=id('issue');db.prepare('INSERT INTO issues VALUES (?,?,?,?,?,?,?,?,?)').run(iid,user.id,clean(input.subject,120),clean(input.description,1200),clean(input.category,40)||'Other','open','',now(),now());broadcast('issue',{id:iid});return send(res,201,{ok:true,id:iid});}
  if(pathname==='/api/issues'&&method==='GET'){if(requireRole(user,['owner','management']))return send(res,200,{issues:db.prepare(`SELECT i.*,u.username,u.name FROM issues i JOIN users u ON u.id=i.reporter_id ORDER BY CASE i.status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 ELSE 2 END,i.created_at DESC`).all()});return send(res,200,{issues:db.prepare('SELECT * FROM issues WHERE reporter_id=? ORDER BY created_at DESC').all(user.id)});}
  match=pathname.match(/^\/api\/issues\/([^/]+)$/);if(match&&method==='PATCH'){if(!requireRole(user,['owner','management']))return send(res,403,{error:'Management access required.'});const input=await readBody(req),status=['open','in_progress','resolved'].includes(input.status)?input.status:'open';db.prepare('UPDATE issues SET status=?,admin_note=?,updated_at=? WHERE id=?').run(status,clean(input.adminNote,600),now(),match[1]);broadcast('issue',{id:match[1]});return send(res,200,{ok:true});}
  if(pathname==='/api/admin/stats'){if(!requireRole(user,['owner','management']))return send(res,403,{error:'Management access required.'});const count=t=>db.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n;return send(res,200,{stats:{users:count('users'),posts:count('posts'),projects:count('projects'),clubs:count('clubs'),events:count('events'),openIssues:db.prepare("SELECT COUNT(*) n FROM issues WHERE status<>'resolved'").get().n},recentUsers:db.prepare('SELECT * FROM users ORDER BY created_at DESC LIMIT 20').all().map(safeUser)});}
  if(pathname==='/api/ai/assist'&&method==='POST'){if(!rate(req,'ai',20,60000))return send(res,429,{error:'AI rate limit reached. Try again shortly.'});const input=await readBody(req);if(!clean(input.text))return send(res,400,{error:'Add text for the AI to work with.'});return send(res,200,{result:await aiAssist(input,user)});}
  return send(res,404,{error:'Route not found.'});
}

const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
function staticFile(res,pathname){const requested=pathname==='/'?'/index.html':pathname,resolved=path.resolve(PUBLIC,`.${requested}`);if(!resolved.startsWith(PUBLIC))return send(res,403,{error:'Forbidden'});const file=fs.existsSync(resolved)&&fs.statSync(resolved).isFile()?resolved:path.join(PUBLIC,'index.html');res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':path.extname(file)==='.html'?'no-cache':'public,max-age=86400'});fs.createReadStream(file).pipe(res);}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))await api(req,res,url.pathname,url);else staticFile(res,url.pathname)}catch(error){if(!error.status)console.error(error);if(!res.headersSent)send(res,error.status||500,{error:error.status?error.message:'Unexpected server error.'})}});
if(require.main===module)server.listen(PORT,HOST,()=>console.log(`College Ox listening on http://${HOST}:${PORT}`));
module.exports={server,db,hashPassword,verifyPassword};
