const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const temp=path.join(__dirname,'.tmp');fs.rmSync(temp,{recursive:true,force:true});fs.mkdirSync(temp,{recursive:true});process.env.DB_FILE=path.join(temp,'test.db');
const {server,db,hashPassword,verifyPassword}=require('../server');
let base;
test.before(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`});
test.after(async()=>{await new Promise(r=>server.close(r));db.close();fs.rmSync(temp,{recursive:true,force:true})});
async function request(url,options={}){const r=await fetch(base+url,options);return {r,data:await r.json()}}
async function owner(){const {r}=await request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:'Navi',password:'Ashish1315e@own'})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]}
async function register(username='student.one'){const {r,data}=await request('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Student One',username,email:`${username.replace('.','')}@college.edu`,password:'long-secure-password'})});assert.equal(r.status,201);return {cookie:r.headers.get('set-cookie').split(';')[0],user:data.user}}

test('passwords use one-way verification',()=>{const hash=hashPassword('correct-horse-battery');assert.equal(hash.includes('correct-horse-battery'),false);assert.equal(verifyPassword('correct-horse-battery',hash),true);assert.equal(verifyPassword('wrong',hash),false)});
test('fresh database is empty except owner identity',async()=>{const cookie=await owner();const {r,data}=await request('/api/bootstrap',{headers:{cookie}});assert.equal(r.status,200);assert.equal(data.posts.length,0);assert.equal(data.projects.length,0);assert.equal(data.clubs.length,0);assert.equal(data.events.length,0);assert.equal(data.announcements.length,0);assert.equal(data.counts.people,1);assert.equal(data.user.role,'owner')});
test('students register, customize profiles, publish, comment, follow and report issues',async()=>{const first=await register();const second=await register('student.two');let response=await request('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json',cookie:first.cookie},body:JSON.stringify({name:'Student One',username:'student.one',bio:'Builder',department:'CSE',year:'2nd year',pronouns:'they/them',location:'North Campus',accent:'#ff6b4a',interests:['Robotics'],links:[{label:'Site',url:'https://example.com'}]})});assert.equal(response.r.status,200);assert.equal(response.data.user.bio,'Builder');response=await request('/api/posts',{method:'POST',headers:{'Content-Type':'application/json',cookie:first.cookie},body:JSON.stringify({body:'A real first post',type:'collab',tags:['Build']})});assert.equal(response.r.status,201);const postId=response.data.post.id;response=await request(`/api/posts/${postId}/comments`,{method:'POST',headers:{'Content-Type':'application/json',cookie:second.cookie},body:JSON.stringify({body:'Count me in'})});assert.equal(response.r.status,201);assert.equal(response.data.post.commentCount,1);response=await request(`/api/users/${first.user.id}/follow`,{method:'POST',headers:{'Content-Type':'application/json',cookie:second.cookie},body:'{}'});assert.equal(response.data.following,true);response=await request('/api/issues',{method:'POST',headers:{'Content-Type':'application/json',cookie:first.cookie},body:JSON.stringify({subject:'A real issue',description:'Something is not working',category:'Technical'})});assert.equal(response.r.status,201)});
test('projects, clubs, events and official notices use real persisted records',async()=>{const user=await register('student.three');let response=await request('/api/projects',{method:'POST',headers:{'Content-Type':'application/json',cookie:user.cookie},body:JSON.stringify({name:'First Build',pitch:'A real project',skills:['Design'],capacity:5})});assert.equal(response.r.status,201);response=await request('/api/clubs',{method:'POST',headers:{'Content-Type':'application/json',cookie:user.cookie},body:JSON.stringify({name:'First Club',description:'A real community',category:'Technology',accent:'#ff6b4a'})});assert.equal(response.r.status,201);response=await request('/api/events',{method:'POST',headers:{'Content-Type':'application/json',cookie:user.cookie},body:JSON.stringify({title:'First Event',description:'Meet together',startsAt:new Date(Date.now()+86400000).toISOString(),location:'Room 1',capacity:40})});assert.equal(response.r.status,201);response=await request('/api/announcements',{method:'POST',headers:{'Content-Type':'application/json',cookie:user.cookie},body:JSON.stringify({title:'No',body:'Not allowed'})});assert.equal(response.r.status,403);const ownerCookie=await owner();response=await request('/api/announcements',{method:'POST',headers:{'Content-Type':'application/json',cookie:ownerCookie},body:JSON.stringify({title:'Official',body:'A real notice',audience:'Everyone'})});assert.equal(response.r.status,201);response=await request('/api/bootstrap',{headers:{cookie:user.cookie}});assert.equal(response.data.projects.length,1);assert.equal(response.data.clubs.length,1);assert.equal(response.data.events.length,1);assert.equal(response.data.announcements.length,1)});
test('owner can delete any post and review issues',async()=>{const cookie=await owner();const post=db.prepare('SELECT id FROM posts LIMIT 1').get();let response=await request(`/api/posts/${post.id}`,{method:'DELETE',headers:{cookie}});assert.equal(response.r.status,200);response=await request('/api/issues',{headers:{cookie}});assert.equal(response.r.status,200);assert.equal(response.data.issues.length,1)});
test('AI endpoint is honest when no provider key is configured',async()=>{const cookie=await owner();const {r,data}=await request('/api/ai/assist',{method:'POST',headers:{'Content-Type':'application/json',cookie},body:JSON.stringify({mode:'rewrite',text:'hello'})});assert.equal(r.status,503);assert.match(data.error,/not configured/i)});
